# This is the directory that the rsync rule will use as the source directory. It shuold be the run directory this workflow.
sourceDir: "/varidata/research/projects/bbc/research/prep_bbc_shared_current"

# This is where the timestamped directories and the 'latest' symlink will be created.
timestamp_dir: "/varidata/research/projects/bbc/versioned_references/"

# Environment modules used.
# Specify all environment modules here instead of within the Snakefile itself to make it easy to look over quickly.
# When aligning using the index files created by this workflow, use the same version aligner as listed here to ensure compatibility.
samtools:   "bbc2/samtools/samtools-1.17"
picard:     "bbc2/picard/picard-3.0.0"
STAR:       "bbc2/STAR/STAR-2.7.10a"
biscuit:    "bbc2/biscuit/biscuit_1_2_0"
bwa:        "bbc2/bwa/bwa-0.7.17"
bowtie2:    "bbc2/bowtie2/bowtie2-2.5.1"
python3:    "bbc2/python3/python-3.11.3"
bismark:    "bbc2/bismark/bismark-0.24.0"
parallel:   "bbc/parallel/parallel-20191122"
gsutil:     "bbc2/gsutil/gsutil-5.26"
seqtk:      "bbc2/seqtk/seqtk-1.3-r115-dirty"
salmon:     "bbc2/salmon/salmon-1.10.0"
kallisto:   "bbc2/kallisto/kallisto-0.50.0"
