# This is the directory that the rsync rule will use as the source directory. It shuold be the run directory this workflow.
sourceDir: "/secondary/projects/bbc/research/prep_bbc_shared_current"

# This is where the timestamped directories and the 'latest' symlink will be created.
timestamp_dir: "/secondary/projects/bbc/research/prep_bbc_shared_timestamped/"

# Environment modules used.
# Specify all environment modules here instead of within the Snakefile itself to make it easy to look over quickly.
# When aligning using the index files created by this workflow, use the same version aligner as listed here to ensure compatibility.
samtools:   "bbc/samtools/samtools-1.9"
picard:     "bbc/picard/picard-2.21.4-SNAPSHOT"
STAR:       "bbc/STAR/STAR-2.7.8a"
bwa:        "bbc/bwa/bwa-0.7.17"
bowtie2:    "bbc/bowtie2/bowtie2-2.4.1"
python3:    "bbc/python3/python-3.8.1"
bismark:    "bbc/bismark/bismark-0.23.0"
kb-python:  "bbc/kb-python/kb-python-0.24.4"
parallel:   "bbc/parallel/parallel-20191122"
gsutil:     "bbc/gsutil/gsutil-4.52" 
